### ISSUE TITLE
marlin issue

### ISSUE THREAD

**Issue by bravecham** [nusgart/uhdl_mister#3]
pin D18 and/or D19 conflicts with another pin on the board.

**Comment by ams** [comment]
Are you sure you filed this with the right project?

**Comment by bravecham** [comment]
Yes I have did the  right thing

**Comment by ams** [comment]
Sorry, that is a bit to terse for me to understand.  How is this related to Marlin?  Seeing that uhdl_mister has no relation to Marlin at all...

Where do you see conflicts? Can you show some sort of output from the synthesize?

**Comment by nusgart** [comment]
Sorry what?  What is marlin?  Also, I didn't change the pinout from the main mister template (although it's very out of date by now). Should I just close this issue?  Also, I am still working on this project, I just don't have much time now because I'm in grad school.

**Comment by ams** [comment]
I think you should close it .. I think it is a mixup.
